server:
  port: 9096
spring:
  application:
    name: H5-test-min
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    include: dev
  redis:
#    host: 192.168.50.180
#    port: 7001
    # 连接超时时长（毫秒）
    timeout: 3s
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1s     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:com/bst/common/mapper/**/*.xml
  type-aliases-package: com.bst.common.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

fast-dfs:
  config:
    connect_timeout: 3
    network_timeout: 30
    charset: UTF-8
    http:
      tracker_http_port: 80
      anti_steal_token: true
      secret_key:  FastDFS1234567890
#    tracker_server: 172.16.18.111:22122
    tracker_server: 192.168.50.182:22122
    group: group1
    httpServerPath: http://192.168.50.182:8888/

platform:
  user:
    interface: http://appapi-dev.safetree.com.cn/usercenter/api/users/get-userinfo-byticket
    timeout: 10800
  connect.timeout: 5000

#goodsInfo的redis存

pay:
  wxpay:
    notify-url: https://mall-test.xueanquan.com/dev/api/wxpay/notify
    pay-id: 1487803572
    app-id: wxd7ef8434e1a91564
    key: HZAKTEST1234567887654321TSETKAZH

swagger:
  description:  使用RESTful APIs
  user-name: 张治冶
  user-email: zhangzhiye@bstyjy.com
  version: 1.0
  user-url: "http://www.baidu.com"
  title: 商城H5接口文档
  service-url: NO terms of service