spring:
  profiles: dev
  datasource:
    mall:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: LearnStudy@123
      jdbc-url: jdbc:mysql://192.168.50.182:3306/mall_data?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
      auto-commit: true
      max-lifetime: 1800000
      pool-name: Mall-HikariCP
      minimum-idle: 5
      idle-timeout: 30000
      maximum-pool-size: 10

    permission:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.50.182:3306/edit_data?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
      username: root
      password: LearnStudy@123
      auto-commit: true
      max-lifetime: 1800000
      pool-name: PM-HikariCP
      minimum-idle: 5
      idle-timeout: 30000
      maximum-pool-size: 10
  resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.path}
  #Redis服务配配置
  redis:
    #    host: 192.168.50.180
    #    port: 7001
    host: 120.79.164.233
    port: 7501
    cluster:
      #      nodes: 192.168.50.180:7001,192.168.50.181:7002,192.168.50.182:7001
      nodes: 120.79.164.233:7501,120.79.164.233:7502,120.79.164.233:7503,120.79.164.233:7504,120.79.164.233:7505,120.79.164.233:7506
      max-redirects: 6
    password: qwsedh./asd0sad;as,.asdgay213y1ad89we
  servlet:
    multipart:
      max-file-size: 50MB

# fastDFS config path
fast-dfs:
  config:
    connect_timeout: 3
    network_timeout: 30
    charset: UTF-8
    http:
      tracker_http_port: 80
      anti_steal_token: true
      secret_key:  FastDFS1234567890
#    tracker_server: 172.16.18.111:22122
    tracker_server: 192.168.50.182:22122
    group: group1
    httpServerPath: http://192.168.50.182:8888/
 #  logger
logging:
  config: classpath:logback-spring.xml
  level:
    com.bst.common.mapper : DEBUG


#goodsInfo的redis存
redis:
  config:
    goodsSpuBaseInfoKey: goods_spu_baseInfo_key
    orderlogistics: ORDERLOGISTICS
    keyGoodssku: GOODSSKU
    keyGoodsspu: GOODSSPU
    pushMysql: PUSHMYSQL
    courierCompanyCode: COURIER_COMPANY_CODE
    courierCompanyName: COURIER_COMPANY_NAME
    postageConfig: POSTAGE_CONFIG
    orderTimeoutDelayKey: order:timeout:delay
    key-goodssku-all: goodssku:all
    goods-shop-base-info-key: goods_shop_base_info_key
debug: true