server:
  port: 9095
spring:
  application:
    name: mall-background
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    include: dev
  resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.path}
  #Redis服务配配置
  redis:
    host: 192.168.50.180
    port: 7001
    # 连接超时时长（毫秒）
    timeout: 3s
    cluster:
      nodes: 192.168.50.180:7001,192.168.50.181:7002,192.168.50.182:7001
      max-redirects: 6
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1s     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
  servlet:
    multipart:
      max-file-size: 50MB


mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:com/bst/common/mapper/**/*.xml
  type-aliases-package: com.bst.common.mapper.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



# fastDFS config path
fast-dfs:
  config:
    connect_timeout: 3
    network_timeout: 30
    charset: UTF-8
    http:
      tracker_http_port: 80
      anti_steal_token: true
      secret_key:  FastDFS1234567890
#    tracker_server: 172.16.18.111:22122
    tracker_server: 192.168.50.182:22122
    group: group1
    httpServerPath: http://192.168.50.182:8888/
 #  logger
logging:
  config: classpath:logback-spring.xml
  level:
    com.bst.common.mapper : DEBUG


#goodsInfo的redis存
debug: true